### DISCUSSION TITLE
N lowest price hours

### DISCUSSION THREAD

**Discussion by nerodoxus** [PiotrMachowski/Home-Assistant-custom-components-TGE#12] [Ideas]
First of all - great work!
It would be useful to mark each hourly data point with a boolean attribute that takes the value true when the price for a given hour is among the N lowest prices of the day. Based on this value, devices can be controlled. N would be configurable.
See https://github.com/jacek2511/ha_rce

**Comment by nerodoxus** [comment]
Alternatively, there is an option to create an automation that turns on a specific switch only during the n hours with the lowest electricity price. input_number.tge_lower_price_hours_limit helper nedds to be defined.

```
alias: Optimize Energy Consumption
triggers:
  - minutes: /5
    trigger: time_pattern
    hours: /1
    seconds: "2"
actions:
  - if:
      - condition: template
        value_template: >
          {% set prices = state_attr('sensor.tge_fixing_1_rate', 'prices_today') %} 
          {% set sorted_prices = prices | sort(attribute='price') %} 
          {% set lowest_price_count = states('input_number.tge_lower_price_hours_limit') | int %}
          {% set lowest_prices = sorted_prices[:lowest_price_count] %} 

          {% for price in lowest_prices %}
            {% if now().strftime('%Y-%m-%dT%H:00:00%z') == price.time.strftime('%Y-%m-%dT%H:00:00%z') %}
              true
            {% endif %}
          {% endfor %}
    then:
      - entity_id: switch.abc
        action: switch.turn_on
        enabled: false
      - action: persistent_notification.create
        metadata: {}
        data:
          message: Energy ON
    else:
      - entity_id: switch.abc
        action: switch.turn_off
        enabled: false
      - action: persistent_notification.create
        metadata: {}
        data:
          message: Energy OFF
```
