### DISCUSSION TITLE
TGE + evcc.io

### DISCUSSION THREAD

**Discussion by tomaszrondio** [PiotrMachowski/Home-Assistant-custom-components-TGE#18] [General]
How to feed prices from TGE to evcc.io

1. use price template if needed. I used this one: https://github.com/PiotrMachowski/Home-Assistant-custom-components-TGE/discussions/14
2. create custom template sensor

```
- platform: template
  sensors:
    energy_forecast:
      friendly_name: "energy forecast"
      value_template: "{{ states('sensor.tge_fixing_1_rate') }}"
      attribute_templates:
        forecast: >-
          {% set prices = state_attr('sensor.tge_fixing_1_rate', 'prices') %}
          {{ "[" }}
          {%- for price in prices -%}
            {{  '{
              "from": "'+(price.time.strftime("%Y-%m-%dT%H:%M:%S%:z")) +'",
              "to": "'+(price.time + timedelta(hours=1)).strftime("%Y-%m-%dT%H:%M:%S%:z") +'",
              "price": '+(price.price) | string +'
            }' }}
            {% if not loop.last %}
              {{","}}
            {% endif %}
          {%- endfor -%}
          {{ "]" }}
```

3. create automation that will publish this sensor to MQTT broker
```
alias: energy forecast mqtt publish
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.tge_fixing_1_rate
conditions: []
actions:
  - action: mqtt.publish
    metadata: {}
    data:
      evaluate_payload: true
      qos: "0"
      retain: true
      topic: energy/forecast
      payload: "{{ state_attr('sensor.energy_forecast', 'forecast') }}"
mode: single
```

4. setup mqtt in evcc according to docs.  If U use home assistant addon it should look like this:
```
mqtt:
  broker: core-mosquitto.local.hass.io:1883
  topic:
  user: USER
  password: PASSWORD
```

5. configure tariff in evcc
```
tariffs:
  currency: PLN
  grid:
    type: custom
    forecast:
      source: mqtt
      topic: energy/forecast
      jq: '[ .[] | {"start": .from, "end": .to, "price": .price} ] | tostring'
```
